create table MATHSUBJECT2
(
  ID VARCHAR2(32) PRIMARY KEY,
  V1 INT NOT NULL,
  V2 INT NOT NULL,
  V3 INT NOT NULL
);
create table MATHSUBJECT3
(
  ID VARCHAR2(32) PRIMARY KEY,
  V1 INT NOT NULL,
  V2 INT NOT NULL,
  V3 INT NOT NULL,
  V4 INT NOT NULL
);